# 指定启用环境为 开发环境 dev
spring:
  profiles:
    active: dev

server:
  port: 80

push:
  iphone: # IosApp：bark
    iphoneBaseUrl: https://api.day.app/4P5DC6jXnLT6Dsm2n9BENe/
    macBaseUrl: https://api.day.app/x6zYYJu4LB8cw6SNWqQ6Ee/
    icon: https://wanfeng-oss.oss-cn-beijing.aliyuncs.com/photos/9bdfc9cc03deddb267edf76f9840f6e7.jpg # 未提供icon时，使用该默认晚风icon～

bili:
  coin: 5 # 每天需要投币的数量。[0,5]。
  gift: true # 送出即将过期礼物。[true,false]
  s2c: true # 银瓜子兑换为硬币。[true,false]
  autoBiCoin: 1 # 月底自动使用B币卷。[{0,自己会使用},{1,给自己充电},{2,兑换成金瓜子}]
  platform: ios # 用户设备的标识[android,ios]
  totalCookie: i-wanna-go-back=-1; buvid_fp_plain=undefined; DedeUserID=287473737; DedeUserID__ckMd5=6119bb91868bfa11; CURRENT_BLACKGAP=0; LIVE_BUVID=AUTO2616590964380964; rpdid=|(mmRk)u~uu0J'uY~|kl|Rmm; CURRENT_PID=c4b2e3e0-ca3c-11ed-b97c-0d30cc0d4e0c; FEED_LIVE_VERSION=V8; hit-new-style-dyn=1; buvid3=5560FB6F-AF10-0493-E00D-516378EA3E1566169infoc; b_nut=1690636066; _uuid=CABC91E2-AAA1-81084-3428-B810244EFA6DC37232infoc; buvid4=D3276578-4407-9E1D-1A12-D1470EB5B04B99252-022072920-aN5fltImCgRRESvvOMIdJsD%2FtyocAbctMgG2OwTErsdOJFoR0lo7jg%3D%3D; b_ut=5; is-2022-channel=1; iflogin_when_web_push=1; hit-dyn-v2=1; CURRENT_QUALITY=64; enable_web_push=ENABLE; header_theme_version=CLOSE; bili_ticket=eyJhbGciOiJIUzI1NiIsImtpZCI6InMwMyIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2OTk2OTg3ODIsImlhdCI6MTY5OTQzOTUyMiwicGx0IjotMX0.8e-mSy3hR6iIfrRlY8DC2tKFzE7tNuFMVRolwbUsabU; bili_ticket_expires=1699698722; fingerprint=cd953cef1e25d227149d58cc8eadc1c4; buvid_fp=cd953cef1e25d227149d58cc8eadc1c4; home_feed_column=4; SESSDATA=30fcb8b8%2C1715138800%2Ce9e5b%2Ab1CjBclLrKZx7ilaH1fGk0zEn25O1oe_a9T0jYdk3MhyQr5nTiguShODc2gdnf3jc9RF8SVnZXZzU3TXFTX0xROUVqYVJ3NG1yeTZBVXd0eGp3ZXR0MnZiMnhQYVE3U3dtTDFyQ21QbTFBSUpZTVNOc1BDRkppTVVFYWN3YVd3alcybkdoSDZLTWxnIIEC; bili_jct=acb0826f4908020f6bbfc55e49925ccf; sid=6hm9jndf; innersign=0; b_lsid=AA63598F_18BB796C78B; PVID=2; CURRENT_FNVAL=16; browser_resolution=1039-726; bp_video_offset_287473737=862216935269466128
  guessCoin: 10
yuanshen:
  cookie: account_id=121545008; ltoken=b3ybdBk9mABE1DptipQUa0n9n4KFvDUqy9X27Rle; ltuid=121545008; cookie_token=5zSFWNtNmTWXuYpF73sqSUTgx6DphEpSdO9Zd1KQ
