# 指定启用环境为 开发环境 dev
spring:
  profiles:
    active: dev

server:
  port: 80

push:
  iphone: # IosApp：bark
    iphoneBaseUrl: https://api.day.app/4P5DC6jXnLT6Dsm2n9BENe/
    macBaseUrl: https://api.day.app/x6zYYJu4LB8cw6SNWqQ6Ee/
    icon: https://wanfeng-oss.oss-cn-beijing.aliyuncs.com/photos/9bdfc9cc03deddb267edf76f9840f6e7.jpg # 未提供icon时，使用该默认晚风icon～

bili:
  coin: 5 # 每天需要投币的数量。[0,5]。
  gift: true # 送出即将过期礼物。[true,false]
  s2c: true # 银瓜子兑换为硬币。[true,false]
  autoBiCoin: 1 # 月底自动使用B币卷。[{0,自己会使用},{1,给自己充电},{2,兑换成金瓜子}]
  platform: ios # 用户设备的标识[android,ios]
  guessCoin: 10