server:
  port: 80
spring:
  cloud:
    gateway:
      routes:
        - id: bilibili
          uri: lb://myweb-crawler
          predicates:
            - Path=/myweb-crawler/**
          filters:
            - StripPrefix=1
        - id: user
          uri: lb://myweb-user
          predicates:
            - Path=/myweb-user/**
          filters:
            - StripPrefix=1
        - id: learn
          uri: lb://myweb-learn
          predicates:
            - Path=/myweb-learn/**
          filters:
            - StripPrefix=1