server:
  port: 9001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.45:3306/my_web?serverTimezone=GMT%2B8
    username: root
    password: liuzhuohao123
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
#      stat-view-servlet: #访问监控网页的登录用户名和密码
#        login-username: druid
#        login-password: druid
#        enabled: true

push:
  iphone: # IosApp：bark
    iphoneBaseUrl: https://api.day.app/4P5DC6jXnLT6Dsm2n9BENe/
    macBaseUrl: https://api.day.app/x6zYYJu4LB8cw6SNWqQ6Ee/
    icon: https://wanfeng-oss.oss-cn-beijing.aliyuncs.com/photos/9bdfc9cc03deddb267edf76f9840f6e7.jpg # 未提供icon时，使用该默认晚风icon～